ExamenSelvinMedina/Models/ErrorViewModel.cs
namespace ExamenSelvinMedina.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamenSelvinMedina/Controllers/HomeController.cs
using ExamenSelvinMedina.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExamenSelvinMedina.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamenSelvinMedina/Controllers/MaestroExamenController.cs
using ExamenSelvinMedina.Infrastucture.Universidad;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExamenSelvinMedina.Controllers
{
    public class MaestroExamenController : Controller
    {
        private readonly UniversidadDbContext _context;

        public MaestroExamenController(UniversidadDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.MaestroExamen.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MaestroExamen == null)
            {
                return NotFound();
            }

            var maestroExamen = await _context.MaestroExamen
                .FirstOrDefaultAsync(m => m.Ncuenta == id);
            if (maestroExamen == null)
            {
                return NotFound();
            }

            return View(maestroExamen);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Ncuenta,NombreCompleto,Profesion,Carrera,Edad")] MaestroExamen maestroExamen)
        {
            if (ModelState.IsValid)
            {
                _context.Add(maestroExamen);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return BadRequest();
            }
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MaestroExamen == null)
            {
                return NotFound();
            }

            var maestroExamen = await _context.MaestroExamen.FindAsync(id);
            if (maestroExamen == null)
            {
                return NotFound();
            }
            return View(maestroExamen);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Ncuenta,NombreCompleto,Profesion,Carrera,Edad")] MaestroExamen maestroExamen)
        {
            if (id != maestroExamen.Ncuenta)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(maestroExamen);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MaestroExamenExists(maestroExamen.Ncuenta))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return BadRequest();
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MaestroExamen == null)
            {
                return NotFound();
            }

            var maestroExamen = await _context.MaestroExamen
                .FirstOrDefaultAsync(m => m.Ncuenta == id);
            if (maestroExamen == null)
            {
                return NotFound();
            }

            return View(maestroExamen);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MaestroExamen == null)
            {
                return Problem("Entity set 'UniversidadDbContext.MaestroExamen'  is null.");
            }
            var maestroExamen = await _context.MaestroExamen.FindAsync(id);
            if (maestroExamen != null)
            {
                _context.MaestroExamen.Remove(maestroExamen);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaestroExamenExists(int id)
        {
            return _context.MaestroExamen.Any(e => e.Ncuenta == id);
        }
    }
}

ExamenSelvinMedina/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
</div>

ExamenSelvinMedina/Views/MaestroExamen/Create.cshtml
@model ExamenSelvinMedina.Infrastucture.Universidad.MaestroExamen

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Maestro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="frmCrear">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ncuenta" class="control-label"></label>
                <input asp-for="Ncuenta" class="form-control" />
                <span asp-validation-for="Ncuenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Profesion" class="control-label"></label>
                <input asp-for="Profesion" class="form-control" />
                <span asp-validation-for="Profesion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Carrera" class="control-label"></label>
                <input asp-for="Carrera" class="form-control" />
                <span asp-validation-for="Carrera" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" value="Crear" id="btnCrear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-default">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamenSelvinMedina/Views/MaestroExamen/Delete.cshtml
@model ExamenSelvinMedina.Infrastucture.Universidad.MaestroExamen

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>¿Estás seguro que deseas eliminar este maestro?</h3>
<div>
    <h4>MaestroExamen</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Profesion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Profesion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carrera)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carrera)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
    </dl>
    
    <form asp-action="Delete" id="frmEliminar">
        <input type="hidden" asp-for="Ncuenta" />
        <input type="button" id="btnEliminar" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-default">Regresar a la lista</a>
    </form>
</div>

ExamenSelvinMedina/Views/MaestroExamen/Details.cshtml
@model ExamenSelvinMedina.Infrastucture.Universidad.MaestroExamen

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Maestro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Profesion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Profesion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carrera)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carrera)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Ncuenta" class="btn btn-primary">Editar</a> |
    <a asp-action="Index" class="btn btn-default">Regresar a la lista</a>
</div>

ExamenSelvinMedina/Views/MaestroExamen/Edit.cshtml
@model ExamenSelvinMedina.Infrastucture.Universidad.MaestroExamen

@{
    ViewData["Title"] = "Edit";
}

<h1>Edición</h1>

<h4>Maestro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" id="frmEditar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Ncuenta" />
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Profesion" class="control-label"></label>
                <input asp-for="Profesion" class="form-control" />
                <span asp-validation-for="Profesion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Carrera" class="control-label"></label>
                <input asp-for="Carrera" class="form-control" />
                <span asp-validation-for="Carrera" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" id="btnEditar" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-default">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamenSelvinMedina/Views/MaestroExamen/Index.cshtml
@model IEnumerable<ExamenSelvinMedina.Infrastucture.Universidad.MaestroExamen>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Crear Nuevo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreCompleto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Profesion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Carrera)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreCompleto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Profesion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Carrera)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Edad)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Ncuenta" class="btn btn-primary">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.Ncuenta" class="btn btn-default">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.Ncuenta" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ExamenSelvinMedina/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenSelvinMedina</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamenSelvinMedina.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamenSelvinMedina</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MaestroExamen" asp-action="Index">Maestros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExamenSelvinMedina - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/general.js" asp-append-version="true"></script>
    <script src="~/js/edit.js" asp-append-version="true"></script>
    <script src="~/js/create.js" asp-append-version="true"></script>
    <script src="~/js/delete.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>